app:
  providers:
    url_generator: true
    session: true
    twig: true
    monolog: false
    doctrine: true

db:
  dbname:   digex
  host:     localhost
  user:     root
  password: root
  entities: [src/Digitas/Demo/Entity]
      