app:
  debug: false
  providers:
    url_generator: true
    session: true
    monolog: false
    twig: false
    doctrine-dbal: false
    doctrine-orm: false

db:
  dbname:   mydb
  host:     localhost
  user:     root
  password: root