app:
  debug: false
  providers:
    twig: true
    url_generator: true
    session: true
    monolog: false
    doctrine-dbal: true

db:
  dbname:   mydb
  host:     localhost
  user:     root
  password: root